FROM ubuntu:14.04.2
MAINTAINER SungKwang Song <saltfactory@gmail.com>

RUN cd /etc/apt && \
     sed -i 's/archive.ubuntu.com/ftp.daum.net/g' sources.list

RUN apt-get update
RUN apt-get install -y ssh-client tree gpa duplicity python-paramiko

RUN useradd -ms /bin/bash mainuser
RUN echo 'mainuser:mainuser' | chpasswd
RUN mv /dev/random /dev/random.bak
RUN ln -s /dev/urandom /dev/random

RUN mkdir /home/mainuser/data
RUN echo "test mainserver data backup" > /home/mainuser/data/seed.data
RUN chown -R mainuser:mainuser /home/mainuser/data

WORKDIR /home/mainuser
